name: envireef
channels:
  - conda-forge
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - matplotlib
  - netCDF4
  - xarray
  - matplotlib
  - numpy
  - scikit-image
  - geopandas
  - shapely
  - cftime
  - cartopy
  - pip:
    - cmocean
    - jupyter-book
    - pyproj
