name: envireef
channels:
  - default
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - matplotlib
  - netCDF4
  - xarray
  - matplotlib
  - numpy>1.10
  - cython>0.15.1
  - cartopy
  - pyproj
  - cftime
  - pip:
    - cmocean
    - jupyter-book
