#######################################################################################
# Book settings
title : Environmental Simulation Modelling
author: Tristan Salles
logo: 'qe-logo-large.png'

# Short description about the book
description: >-
  A brief introduction to Python programming for scientific applications.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/TristanSalles/EnviReef
  path_to_book                : "book"
  branch                      : main

launch_buttons:
  notebook_interface: "jupyterlab"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
   - docs/ref.bib
